
--PAINT-CONDITION
DROP TABLE IOWA_TRANSFORM.BPAINT CASCADE CONSTRAINTS;
CREATE TABLE IOWA_TRANSFORM.BPAINT
(
        USER_ID                     INT NOT NULL PRIMARY KEY,
        ROUTE_TYPE              VARCHAR2(4),
        ROUTE_NAME             VARCHAR2(255), 
        ROUTE_DIR                VARCHAR2(4),      
        ST_POST                   VARCHAR2(255),
        ED_POST                   VARCHAR2(255),
        ST_OFFSET                NUMBER(10),
        ED_OFFSET                NUMBER(10),
        PAINT_VALUE              NUMBER(10),
        DATUM_REFERENCE               CLOB,
        GEOMETRY                 MDSYS.SDO_GEOMETRY,
        GEO_EXTENT              VARCHAR2(255),
        SYSTEM_NAME          VARCHAR2(255)
);
COMMIT;

    --INSERT INTO PAINT-CONDITION  [E-BOUND] 
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
    (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (1, 'I', '80', 'E', '10', '25', .0, .0, 20, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (2, 'I', '80', 'E', '25', '50', .0, .0, 62, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (3, 'I', '80', 'E', '50', '75', .0, .0, 35, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (4, 'I', '80', 'E', '75', '100', .0, .0, 76, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
  
    --INSERT INTO PAINT-CONDITION  [W-BOUND] 
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (5, 'I', '80', 'W', '10', '16', .0, .0, 41, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (6, 'I', '80', 'W', '16', '54', .0, .0, 80, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (7, 'I', '80', 'W', '54', '79', .0, .0, 18, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAINT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, PAINT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (8, 'I', '80', 'W', '79', '100', .0, .0, 20, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
    --Creating MetaData and Spatial Index for resulting Paint-Condition
    DELETE FROM MDSYS.USER_SDO_GEOM_METADATA where table_name = 'BPAINT';
    COMMIT;
    INSERT INTO USER_SDO_GEOM_METADATA values('BPAINT', 'GEOMETRY',          
     MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -2147483648, 2147483647, 0.000005), 
     MDSYS.SDO_DIM_ELEMENT('Y',  -2147483648, 2147483647, 0.000005)), 1050010 );
    COMMIT;
    CREATE INDEX IOWA_TRANSFORM.BPAINT_SPIDX ON
    IOWA_TRANSFORM.BPAINT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX
    PARAMETERS('sdo_non_leaf_tbl=TRUE');

--Salt
DROP TABLE IOWA_TRANSFORM.BSALT CASCADE CONSTRAINTS;
CREATE TABLE IOWA_TRANSFORM.BSALT
(
        USER_ID                     INT NOT NULL PRIMARY KEY,
        ROUTE_TYPE              VARCHAR2(4),
        ROUTE_NAME             VARCHAR2(255), 
        ROUTE_DIR                VARCHAR2(4),      
        ST_POST                   VARCHAR2(255),
        ED_POST                   VARCHAR2(255),
        ST_OFFSET                NUMBER(10),
        ED_OFFSET                NUMBER(10),
        SALT_VALUE              NUMBER(10),
        DATUM_REFERENCE               CLOB,
        GEOMETRY                 MDSYS.SDO_GEOMETRY,
        GEO_EXTENT              VARCHAR2(255),
        SYSTEM_NAME          VARCHAR2(255)
);
COMMIT;

    --INSERT INTO SALT  [E-BOUND] 
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (1, 'I', '80', 'E', '10', '36', .0, .0, 5, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (2, 'I', '80', 'E', '36', '62', .0, .0, 15, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (3, 'I', '80', 'E', '62', '71', .0, .0, 8, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (4, 'I', '80', 'E', '71', '100', .0, .0, 11, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
 
    --INSERT INTO SALT  [S-BOUND] 
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
    (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (5, 'I', '80', 'W', '10', '40', .0, .0, 7, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (6, 'I', '80', 'W', '40', '68', .0, .0, 10, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BSALT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, SALT_VALUE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (7, 'I', '80', 'W', '68', '100', .0, .0, 8, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
    
    
    --Pavement Material--Creating MetaData and Spatial Index for salt
    DELETE FROM MDSYS.USER_SDO_GEOM_METADATA where table_name = 'BSALT';
    COMMIT;
    INSERT INTO USER_SDO_GEOM_METADATA values('BSALT', 'GEOMETRY',         
     MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -2147483648, 2147483647, 0.000005), 
     MDSYS.SDO_DIM_ELEMENT('Y',  -2147483648, 2147483647, 0.000005)), 1050010 );
    COMMIT;
    CREATE INDEX IOWA_TRANSFORM.BSALT_SPIDX ON
    IOWA_TRANSFORM.BSALT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX
    PARAMETERS('sdo_non_leaf_tbl=TRUE');
DROP TABLE IOWA_TRANSFORM.BPAVEMENT CASCADE CONSTRAINTS;
CREATE TABLE IOWA_TRANSFORM.BPAVEMENT
(
        USER_ID                     INT NOT NULL PRIMARY KEY,
        ROUTE_TYPE              VARCHAR2(4),
        ROUTE_NAME             VARCHAR2(255), 
        ROUTE_DIR                VARCHAR2(4),      
        ST_POST                   VARCHAR2(255),
        ED_POST                   VARCHAR2(255),
        ST_OFFSET                NUMBER(10),
        ED_OFFSET                NUMBER(10),
        MATE_TYPE               VARCHAR2(20),
        DATUM_REFERENCE               CLOB,
        GEOMETRY                 MDSYS.SDO_GEOMETRY,
        GEO_EXTENT              VARCHAR2(255),
        SYSTEM_NAME          VARCHAR2(255)
);
COMMIT;

    --INSERT INTO SALT  [E-BOUND] 
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (1, 'I', '80', 'E', '10', '20', .0, .0, 'ACC II', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (2, 'I', '80', 'E', '20', '41', .0, .0, 'ACC I', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (3, 'I', '80', 'E', '41', '65', .0, .0, 'ACC III', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (4, 'I', '80', 'E', '65', '100', .0, .0, 'PCC', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    

    --INSERT INTO PAVEMENT  [W-BOUND] 
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
    (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (5, 'I', '80', 'W', '10', '39', .0, .0, 'ACC II', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (6, 'I', '80', 'W', '39', '61', .0, .0, 'PCC', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (7, 'I', '80', 'W', '61', '78', .0, .0, 'ACC III', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BPAVEMENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET, MATE_TYPE,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (8, 'I', '80', 'W', '78', '100', .0, .0, 'ACC I', '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
    --Creating MetaData and Spatial Index for Pavement
    DELETE FROM MDSYS.USER_SDO_GEOM_METADATA where table_name = 'BPAVEMENT';
    COMMIT;
    INSERT INTO USER_SDO_GEOM_METADATA values('BPAVEMENT', 'GEOMETRY',          --user_sdo_geom_metadata = view in mdsys schema
     MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -2147483648, 2147483647, 0.000005), 
     MDSYS.SDO_DIM_ELEMENT('Y',  -2147483648, 2147483647, 0.000005)), 1050010 );
    COMMIT;
    CREATE INDEX IOWA_TRANSFORM.BPAVEMENT_SPIDX ON
    IOWA_TRANSFORM.BPAVEMENT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX
    PARAMETERS('sdo_non_leaf_tbl=TRUE');


--RESILIENT MODULES
DROP TABLE IOWA_TRANSFORM.BRESILIENT CASCADE CONSTRAINTS;
CREATE TABLE IOWA_TRANSFORM.BRESILIENT
(
        USER_ID                     INT NOT NULL PRIMARY KEY,
        ROUTE_TYPE              VARCHAR2(4),
        ROUTE_NAME             VARCHAR2(255), 
        ROUTE_DIR                VARCHAR2(4),      
        ST_POST                   VARCHAR2(255),
        ED_POST                   VARCHAR2(255),
        ST_OFFSET                NUMBER(10),
        ED_OFFSET                NUMBER(10),
        STRENGTH                 NUMBER(10),            --unit in MPa
        DATUM_REFERENCE               CLOB,
        GEOMETRY                 MDSYS.SDO_GEOMETRY,
        GEO_EXTENT              VARCHAR2(255),
        SYSTEM_NAME          VARCHAR2(255)
);
COMMIT;

    --INSERT INTO RESILIENT  [E-BOUND] 
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (1, 'I', '80', 'E', '10', '20', .0, .0, 4250, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (2, 'I', '80', 'E', '20', '41', .0, .0, 4500, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (3, 'I', '80', 'E', '41', '65', .0, .0, 3900, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
     SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (4, 'I', '80', 'E', '65', '100', .0, .0, 2632, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    

    --INSERT INTO RESILIENT  [W-BOUND] 
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
    (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (5, 'I', '80', 'W', '10', '39', .0, .0, 4530, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (6, 'I', '80', 'W', '39', '61', .0, .0, 3320, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (7, 'I', '80', 'W', '61', '76', .0, .0, 3850, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    SET DEFINE OFF;
    Insert into IOWA_TRANSFORM.BRESILIENT
     (USER_ID, ROUTE_TYPE, ROUTE_NAME, ROUTE_DIR, ST_POST,  ED_POST, ST_OFFSET, ED_OFFSET,  STRENGTH,  DATUM_REFERENCE,  GEOMETRY,  GEO_EXTENT,  SYSTEM_NAME)
    Values (8, 'I', '80', 'W', '76', '100', .0, .0, 4024, '', '', 'STATE OF IOWA', 'INTERSTATE, US, STATE SIGNED');
    COMMIT;
    
    --Creating MetaData and Spatial Index for Resilient Modulus
   DELETE FROM MDSYS.USER_SDO_GEOM_METADATA where table_name = 'BRESILIENT';
    COMMIT;
    INSERT INTO USER_SDO_GEOM_METADATA values('BRESILIENT', 'GEOMETRY',          --user_sdo_geom_metadata = view in mdsys schema
     MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -2147483648, 2147483647, 0.000005), 
     MDSYS.SDO_DIM_ELEMENT('Y',  -2147483648, 2147483647, 0.000005)), 1050010 );
    COMMIT;
    CREATE INDEX IOWA_TRANSFORM.BRESILIENT_SPIDX ON
    IOWA_TRANSFORM.BRESILIENT(GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX
    PARAMETERS('sdo_non_leaf_tbl=TRUE');